# ***DATA EXPLORATION***

This notebook is to explore our dataset and work on it by applying preprocessing methods to make it fit for our **ML Model** which will be in another notebook

### **Importing libraries**

Firstly we will import the required libraries for this project

In [64]:
import os
import kagglehub
import pandas as pd

### **Importing dataset**

We will now import our dataset from Kaggle itself

In [63]:
path = kagglehub.dataset_download("atomicd/retail-store-inventory-and-demand-forecasting")

In [3]:
print(path)

C:\Users\aaryan\.cache\kagglehub\datasets\atomicd\retail-store-inventory-and-demand-forecasting\versions\8

In [6]:
print(os.listdir(path))

['sales_data.csv']

In [7]:
df = pd.read_csv(path + "/sales_data.csv")

In [8]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,Weather Condition,Promotion,Competitor Pricing,Seasonality,Epidemic,Demand
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,Snowy,0,85.73,Winter,0,115
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,Snowy,1,92.02,Winter,0,229
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,Snowy,1,60.08,Winter,0,157
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,Snowy,0,85.19,Winter,0,52
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,Snowy,0,51.63,Winter,0,59

### **Feature engineering**

Now we will understand our dataset and perform feature engineering

In [35]:
df.shape

(76000, 18)

In [36]:
df.describe()

,Date,Inventory Level,Units Sold,Units Ordered,Price,Discount,Promotion,Competitor Pricing,Epidemic,Demand,Year,Month
count,76000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000,76000.000000
mean,2023-01-15 12:00:00,301.062842,88.827316,89.090645,67.726028,9.087039,0.328947,69.454029,0.200000,104.317158,2022.559211,6.307895
min,2022-01-01 00:00:00,0.000000,0.000000,0.000000,4.740000,0.000000,0.000000,4.290000,0.000000,4.000000,2022.000000,1.000000
25%,2022-07-09 18:00:00,136.000000,58.000000,0.000000,31.997500,5.000000,0.000000,32.620000,0.000000,71.000000,2022.000000,3.000000
50%,2023-01-15 12:00:00,227.000000,84.000000,0.000000,64.500000,10.000000,0.000000,65.700000,0.000000,100.000000,2023.000000,6.000000
75%,2023-07-24 06:00:00,408.000000,114.000000,121.000000,95.830000,10.000000,1.000000,97.932500,0.000000,133.000000,2023.000000,9.000000
max,2024-01-30 00:00:00,2267.000000,426.000000,1616.000000,228.030000,25.000000,1.000000,261.220000,1.000000,430.000000,2024.000000,12.000000
std,NaN,226.510161,43.994525,162.404627,39.377899,7.475781,0.469834,40.943818,0.400003,46.964801,0.570479,3.546325

In [37]:
df.columns.tolist()

['Date',
 'Store ID',
 'Product ID',
 'Category',
 'Region',
 'Inventory Level',
 'Units Sold',
 'Units Ordered',
 'Price',
 'Discount',
 'Weather Condition',
 'Promotion',
 'Competitor Pricing',
 'Seasonality',
 'Epidemic',
 'Demand',
 'Year',
 'Month']

In [38]:
df.dtypes

Date                  datetime64[us]
Store ID                         str
Product ID                       str
Category                         str
Region                           str
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Price                        float64
Discount                       int64
Weather Condition                str
Promotion                      int64
Competitor Pricing           float64
Seasonality                      str
Epidemic                       int64
Demand                         int64
Year                           int32
Month                          int32
dtype: object

As we can see, the datatype of the `Date` column is `str` or string

We will now convert it into a `datetime` format

We are doing this so we can extract more information out of it such as year and month

In [39]:
df["Date"] = pd.to_datetime(df["Date"])

In [40]:
df.dtypes

Date                  datetime64[us]
Store ID                         str
Product ID                       str
Category                         str
Region                           str
Inventory Level                int64
Units Sold                     int64
Units Ordered                  int64
Price                        float64
Discount                       int64
Weather Condition                str
Promotion                      int64
Competitor Pricing           float64
Seasonality                      str
Epidemic                       int64
Demand                         int64
Year                           int32
Month                          int32
dtype: object

In [41]:
df.isnull().sum()

Date                  0
Store ID              0
Product ID            0
Category              0
Region                0
Inventory Level       0
Units Sold            0
Units Ordered         0
Price                 0
Discount              0
Weather Condition     0
Promotion             0
Competitor Pricing    0
Seasonality           0
Epidemic              0
Demand                0
Year                  0
Month                 0
dtype: int64

We can also see that our dataset has no `NULL` values 

This makes it easier for us as we don't have to remove or fix any rows

In [42]:
df.duplicated().sum()

np.int64(0)

We can also see that our dataset has no duplicate values which makes it easier for us to work with

Now we will extract the year, month, day and weekday from the `Date` column

We will put this new information into their new respective columns

In [43]:
df["Date"].head()

0   2022-01-01
1   2022-01-01
2   2022-01-01
3   2022-01-01
4   2022-01-01
Name: Date, dtype: datetime64[us]

In [48]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Day"] = df["Date"].dt.day
df["Weekday"] = df["Date"].dt.day_name()

In [49]:
df[["Date", "Year", "Month", "Day", "Weekday"]].head()

        Date  Year  Month  Day   Weekday
0 2022-01-01  2022      1    1  Saturday
1 2022-01-01  2022      1    1  Saturday
2 2022-01-01  2022      1    1  Saturday
3 2022-01-01  2022      1    1  Saturday
4 2022-01-01  2022      1    1  Saturday

In [50]:
df["Year"].value_counts()

Year
2022    36500
2023    36500
2024     3000
Name: count, dtype: int64

In [51]:
df["Month"].value_counts()

Month
1     9200
3     6200
5     6200
7     6200
8     6200
10    6200
12    6200
4     6000
6     6000
9     6000
11    6000
2     5600
Name: count, dtype: int64

In [53]:
df["Weekday"].value_counts()

Weekday
Saturday     10900
Sunday       10900
Monday       10900
Tuesday      10900
Wednesday    10800
Thursday     10800
Friday       10800
Name: count, dtype: int64

In [74]:
df["Store ID"].value_counts()

Store ID
S001    15200
S002    15200
S003    15200
S004    15200
S005    15200
Name: count, dtype: int64

In [75]:
df["Product ID"].value_counts()

Product ID
P0001    3800
P0002    3800
P0003    3800
P0004    3800
P0005    3800
P0006    3800
P0007    3800
P0008    3800
P0009    3800
P0010    3800
P0011    3800
P0012    3800
P0013    3800
P0014    3800
P0015    3800
P0016    3800
P0017    3800
P0018    3800
P0019    3800
P0020    3800
Name: count, dtype: int64

In [76]:
df["Category"].value_counts()

Category
Groceries      30400
Furniture      13680
Clothing       12160
Toys           10640
Electronics     9120
Name: count, dtype: int64

In [78]:
df["Weather Condition"].value_counts()

Weather Condition
Cloudy    24360
Sunny     22980
Rainy     17500
Snowy     11160
Name: count, dtype: int64

In [79]:
df["Seasonality"].value_counts()

Seasonality
Winter    21000
Spring    18400
Summer    18400
Autumn    18200
Name: count, dtype: int64

In our dataset we have 2 columns which are `Price` and `Discount`

`Price` = this tells the price of the product

`Discount` = this tells the discount % applied on the product

In [56]:
df[["Price", "Discount"]].head()

   Price  Discount
0  72.72         5
1  80.16        15
2  62.94        10
3  87.63        10
4  54.41         0

What we'll do here is create a new column named `Discounted Price`

This will contain the `price - discount` as the new price

In [57]:
df["DiscountedPrice"] = df["Price"] * (1 - df["Discount"] / 100)

In [58]:
df[["Price", "Discount", "DiscountedPrice"]].head()

   Price  Discount  DiscountedPrice
0  72.72         5           69.084
1  80.16        15           68.136
2  62.94        10           56.646
3  87.63        10           78.867
4  54.41         0           54.410

In our dataset regarding the units sold, we have 2 important columns

`Units Sold` = this tells the no. of units sold

`Inventory Level` = this tells the total no. of units we had

In [59]:
df[["Units Sold", "Inventory Level"]].head()

   Units Sold  Inventory Level
0         102              195
1         117              117
2         114              247
3          45              139
4          65              152

From this we will extract a new column called `Sell-Through Rate`

What it tells is the % of units sold from the entire inventory we had

This helps us understand the demand of that specific product

In [60]:
df["SellThroughRate"] = df["Units Sold"] / df["Inventory Level"]

In [61]:
df[["Units Sold", "Inventory Level", "SellThroughRate"]].head()

   Units Sold  Inventory Level  SellThroughRate
0         102              195         0.523077
1         117              117         1.000000
2         114              247         0.461538
3          45              139         0.323741
4          65              152         0.427632

Now that we have made a couple of changes in our dataset let us look the entire dataset

In [62]:
df.head()

,Date,Store ID,Product ID,Category,Region,Inventory Level,Units Sold,Units Ordered,Price,Discount,...,Competitor Pricing,Seasonality,Epidemic,Demand,Year,Month,Day,Weekday,DiscountedPrice,SellThroughRate
0,2022-01-01,S001,P0001,Electronics,North,195,102,252,72.72,5,...,85.73,Winter,0,115,2022,1,1,Saturday,69.084,0.523077
1,2022-01-01,S001,P0002,Clothing,North,117,117,249,80.16,15,...,92.02,Winter,0,229,2022,1,1,Saturday,68.136,1.000000
2,2022-01-01,S001,P0003,Clothing,North,247,114,612,62.94,10,...,60.08,Winter,0,157,2022,1,1,Saturday,56.646,0.461538
3,2022-01-01,S001,P0004,Electronics,North,139,45,102,87.63,10,...,85.19,Winter,0,52,2022,1,1,Saturday,78.867,0.323741
4,2022-01-01,S001,P0005,Groceries,North,152,65,271,54.41,0,...,51.63,Winter,0,59,2022,1,1,Saturday,54.410,0.427632

Now let us check the different categories in our dataset along with the different stats about their demands

This will help us know which categories have most demands

In [65]:
df.groupby("Category")["Demand"].agg(["mean", "median", "std"]).sort_values("mean", ascending=False)

                   mean  median        std
Category
Groceries    120.976447   116.0  48.362730
Clothing     112.619737   109.0  41.022968
Electronics   97.482018    95.0  40.557859
Toys          92.606955    92.0  46.170390
Furniture     73.581140    72.0  32.336141

Now let us check the demand based on the region and season and see how different geographical features affect the demand

In [68]:
df.groupby(["Region", "Seasonality"])["Demand"].mean()

Region  Seasonality
East    Autumn         106.353297
        Spring         100.168478
        Summer         115.388315
        Winter         104.273571
North   Autumn         103.065797
        Spring          97.399457
        Summer         112.843750
        Winter         102.017738
South   Autumn         104.464560
        Spring         100.328804
        Summer         115.089946
        Winter         107.733095
West    Autumn         100.165385
        Spring          93.219293
        Summer         108.111141
        Winter         100.988810
Name: Demand, dtype: float64

**Highest:** Summer (in all regions)

**Lowest:** Spring (in all regions)

Now lets check the demand of each category month wise to help us understand which categories have the most demand in which months

In [69]:
pd.pivot_table(df, values="Demand", index="Month", columns="Category", aggfunc="mean")

Category    Clothing  Electronics  Furniture   Groceries        Toys
Month
1         126.997962    99.519022  75.690821  117.399457   94.242236
2         128.966518    84.184524  61.625992  103.522768   68.885204
3         105.835685   108.120968  84.015233  126.561694  128.273041
4         106.972917    85.916667  63.005556  105.111250   85.753571
5         108.650202    79.577957  56.036738   98.637903   71.756912
6         105.670833   106.922222  79.908333  147.772500  100.825000
7         107.838710    87.418011  66.156810  128.744355   74.366359
8         107.871976   109.733871  83.524194  149.875403  102.794931
9         105.118750   105.015278  81.854630  122.239167  102.722619
10        107.113911    89.354839  69.279570  109.765323   80.857143
11        106.306250   107.495833  82.033333  122.121250  100.138095
12        127.865927   104.750000  78.067204  120.438306   98.194700

Similarly, we will check the category wise demand in different regions as well

In [70]:
pd.pivot_table(df, values="Demand", index="Region", columns="Category", aggfunc="mean")

Category    Clothing  Electronics  Furniture   Groceries       Toys
Region
East      109.455263   107.982456  73.414912  121.114620  92.079825
North     123.052303    93.579211  73.709962  120.829030  92.690789
South     108.038421    93.957456  73.294737  120.585855  92.910526
West      110.120789    96.068421  73.564474  121.582143        NaN

We can see that in the west region there is no demand for `Toys`

We should also cross-check this by further checking the dataset for demand of `Toys` in `West` region

In [72]:
df[(df["Region"] == "West") & (df["Category"] == "Toys")]

Empty DataFrame
Columns: [Date, Store ID, Product ID, Category, Region, Inventory Level, Units Sold, Units Ordered, Price, Discount, Weather Condition, Promotion, Competitor Pricing, Seasonality, Epidemic, Demand, Year, Month, Day, Weekday, DiscountedPrice, SellThroughRate]
Index: []

[0 rows x 22 columns]

Now that most of our data exploration and feature engineering is done, we can move on to data visualisations in which we'll use `seaborn` and `matplotlib` to generate visualisations to understand the dataset even better

So for that, we will export the edited dataset

In [73]:
df.to_csv("cleaned_sales_data.csv", index=False)